### ISSUE TITLE
Unable To Run Site Locally

### ISSUE THREAD

**Issue by bensternthal** [ceph/ceph.io#748]
On a fresh install, running the site locally via ```npm run dev``` results in the following error when I view a page in a browser:

```
[Browsersync] Serving files from: dist
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at res.writeHead (/Users/ben/Documents/Dev/ceph.io/node_modules/resp-modifier/index.js:140:27)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:764:28)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at onstat (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:727:26)
    at FSReqCallback.oncomplete (node:fs:197:21)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at onstat (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:727:26)
    at FSReqCallback.oncomplete (node:fs:197:21)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at onstat (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:727:26)
    at FSReqCallback.oncomplete (node:fs:197:21)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at onstat (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:727:26)
    at FSReqCallback.oncomplete (node:fs:197:21)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at onstat (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:727:26)
    at FSReqCallback.oncomplete (node:fs:197:21)
Error [ERR_HTTP_HEADERS_SENT]: Cannot write headers after they are sent to the client
    at ServerResponse.writeHead (node:_http_server:345:11)
    at /Users/ben/Documents/Dev/ceph.io/.eleventy.js:139:15
    at call (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:239:7)
    at next (/Users/ben/Documents/Dev/ceph.io/node_modules/connect/index.js:183:5)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:519:28)
    at SendStream.error (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:421:12)
    at onstat (/Users/ben/Documents/Dev/ceph.io/node_modules/send/index.js:727:26)
    at FSReqCallback.oncomplete (node:fs:197:21)
```

**Comment by Thingee** [comment]
Hi @bensternthal, thank you for reporting this. I was not able to replicate issue or #749 on Ubuntu 24.04 with a fresh install. What operating system/environment are you using?

I'm not surprised that there would be issues due to outdated dependencies that I just created an issue for #822.

**Comment by Thingee** [comment]
I was able to verify this issue when visiting HTTP://localhost:8080 specifically. I also verified that #847 will take care of this.
